"""enhance report models and add store report

Revision ID: 163d3125e872
Revises: dced2ffc0326
Create Date: 2025-01-05 18:25:55.022859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '163d3125e872'
down_revision = 'dced2ffc0326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_report', schema=None) as batch_op:
        batch_op.alter_column('performance_metrics',
                            existing_type=sa.JSON(),
                            type_=sa.Text(),
                            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_report', schema=None) as batch_op:
        batch_op.alter_column('performance_metrics',
                            existing_type=sa.Text(),
                            type_=sa.JSON(),
                            existing_nullable=True)
    # ### end Alembic commands ###
