"""initial migration

Revision ID: 196313c22a8e
Revises: 
Create Date: 2025-01-27 17:36:32.455949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196313c22a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=True),
    sa.Column('marketplace', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_store_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('active_store_id', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_store_id'], ['stores.id'], name='fk_user_active_store'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('advertising_reports',
    sa.Column('campaign_name', sa.String(length=100), nullable=False),
    sa.Column('ad_group_name', sa.String(length=100), nullable=False),
    sa.Column('targeting_type', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('search_term', sa.String(length=200), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acos', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertising_reports', schema=None) as batch_op:
        batch_op.create_index('idx_advertising_campaign', ['campaign_name'], unique=False)
        batch_op.create_index('idx_advertising_store_date', ['store_id', 'date'], unique=False)

    op.create_table('asin_kategoriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin')
    )
    op.create_table('business_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('session_percentage', sa.Float(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('page_views_percentage', sa.Float(), nullable=False),
    sa.Column('buy_box_percentage', sa.Float(), nullable=False),
    sa.Column('units_ordered', sa.Integer(), nullable=False),
    sa.Column('unit_session_percentage', sa.Float(), nullable=False),
    sa.Column('ordered_product_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_order_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csv_files', schema=None) as batch_op:
        batch_op.create_index('idx_csv_files_type_date', ['file_type', 'created_at'], unique=False)
        batch_op.create_index('idx_csv_files_user_store', ['user_id', 'store_id'], unique=False)

    op.create_table('inventory_reports',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('asin', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mfn_listing_exists', sa.Boolean(), nullable=False),
    sa.Column('mfn_fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_listing_exists', sa.Boolean(), nullable=False),
    sa.Column('afn_warehouse_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_unsellable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_total_quantity', sa.Integer(), nullable=False),
    sa.Column('per_unit_volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_reports', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_asin', ['asin'], unique=False)
        batch_op.create_index('idx_inventory_sku', ['sku'], unique=False)
        batch_op.create_index('idx_inventory_store_date', ['store_id', 'date'], unique=False)

    op.create_table('return_reports',
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('asin', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('return_reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('return_center', sa.String(length=200), nullable=False),
    sa.Column('return_carrier', sa.String(length=100), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_reports', schema=None) as batch_op:
        batch_op.create_index('idx_return_asin', ['asin'], unique=False)
        batch_op.create_index('idx_return_order', ['order_id'], unique=False)
        batch_op.create_index('idx_return_sku', ['sku'], unique=False)
        batch_op.create_index('idx_return_store_date', ['store_id', 'return_date'], unique=False)

    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csv_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_history')
    with op.batch_alter_table('return_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_return_store_date')
        batch_op.drop_index('idx_return_sku')
        batch_op.drop_index('idx_return_order')
        batch_op.drop_index('idx_return_asin')

    op.drop_table('return_reports')
    with op.batch_alter_table('inventory_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_store_date')
        batch_op.drop_index('idx_inventory_sku')
        batch_op.drop_index('idx_inventory_asin')

    op.drop_table('inventory_reports')
    with op.batch_alter_table('csv_files', schema=None) as batch_op:
        batch_op.drop_index('idx_csv_files_user_store')
        batch_op.drop_index('idx_csv_files_type_date')

    op.drop_table('csv_files')
    op.drop_table('business_reports')
    op.drop_table('asin_kategoriler')
    with op.batch_alter_table('advertising_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_advertising_store_date')
        batch_op.drop_index('idx_advertising_campaign')

    op.drop_table('advertising_reports')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('categories')
    # ### end Alembic commands ###
