"""Remove active_store_id from User model

Revision ID: 2a27991a7035
Revises: c705316555fd
Create Date: 2025-01-05 15:38:42.310861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a27991a7035'
down_revision = 'c705316555fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_store_id', type_='foreignkey')
        batch_op.drop_column('active_store_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_store_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_active_store_id', 'store', ['active_store_id'], ['id'])

    # ### end Alembic commands ###
