"""update business report model to sqlalchemy 2.0

Revision ID: 9049d21383f0
Revises: c1f75e79fa45
Create Date: 2025-01-30 17:43:31.357781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9049d21383f0'
down_revision = 'c1f75e79fa45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('asin',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('ordered_product_sales',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('page_views')
        batch_op.drop_column('units_ordered_b2b')
        batch_op.drop_column('ordered_product_sales_b2b')
        batch_op.drop_column('unit_session_percentage_b2b')
        batch_op.drop_column('unit_session_percentage')
        batch_op.drop_column('session_percentage')
        batch_op.drop_column('total_order_items_b2b')
        batch_op.drop_column('page_views_percentage')
        batch_op.drop_column('buy_box_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_box_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('page_views_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('total_order_items_b2b', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('session_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('unit_session_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('unit_session_percentage_b2b', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('ordered_product_sales_b2b', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('units_ordered_b2b', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('page_views', sa.INTEGER(), nullable=False))
        batch_op.alter_column('ordered_product_sales',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('asin',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('conversion_rate')

    # ### end Alembic commands ###
