"""initial migration

Revision ID: 940dc9eb1f83
Revises: 
Create Date: 2025-01-13 17:58:57.923749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940dc9eb1f83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertising_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.String(length=100), nullable=False),
    sa.Column('ad_group_name', sa.String(length=100), nullable=False),
    sa.Column('targeting_type', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('search_term', sa.String(length=200), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acos', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('units_ordered', sa.Integer(), nullable=False),
    sa.Column('ordered_product_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_order_items', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mfn_listing_exists', sa.Boolean(), nullable=False),
    sa.Column('mfn_fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_listing_exists', sa.Boolean(), nullable=False),
    sa.Column('afn_warehouse_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_unsellable_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('afn_total_quantity', sa.Integer(), nullable=False),
    sa.Column('per_unit_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('return_reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('return_center', sa.String(length=200), nullable=False),
    sa.Column('return_carrier', sa.String(length=100), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('performance_metrics', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('customer_satisfaction', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('account_health', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_report')
    op.drop_table('return_report')
    op.drop_table('inventory_report')
    op.drop_table('csv_file')
    op.drop_table('business_report')
    op.drop_table('advertising_report')
    op.drop_table('store')
    op.drop_table('user')
    # ### end Alembic commands ###
