"""add is_active field to user model

Revision ID: bebf441c3555
Revises: e454ebfdac94
Create Date: 2025-01-30 20:32:23.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebf441c3555'
down_revision = 'e454ebfdac94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE users SET is_active = 1 WHERE is_active IS NULL")
    
    # 3. Now make it not nullable with a default value
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               nullable=False,
               existing_server_default=None,
               server_default=sa.true())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
