"""add marketplace field to Store model

Revision ID: c1f75e79fa45
Revises: 32bd547c545f
Create Date: 2025-01-30 17:30:28.483491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f75e79fa45'
down_revision = '32bd547c545f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('marketplace')

    # ### end Alembic commands ###
