"""Add active_store_id to User model

Revision ID: c705316555fd
Revises: 
Create Date: 2025-01-05 15:29:08.066825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c705316555fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_active_store_id', 'store', ['active_store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_store_id', type_='foreignkey')
        batch_op.drop_column('active_store_id')

    # ### end Alembic commands ###
