"""Update store and report models

Revision ID: d1b322cc96c4
Revises: 2a27991a7035
Create Date: 2025-01-05 15:56:31.281609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b322cc96c4'
down_revision = '2a27991a7035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertising_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roi', sa.Numeric(precision=6, scale=4), nullable=False))
        batch_op.alter_column('campaign_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('sales',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('acos',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('roas')

    with op.batch_alter_table('business_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('returns', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('page_views', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sessions', sa.Integer(), nullable=False))
        batch_op.alter_column('units_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               nullable=False)
        batch_op.drop_column('sales')
        batch_op.drop_column('impressions')
        batch_op.drop_column('date')
        batch_op.drop_column('clicks')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('inventory_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('units_available', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('units_inbound', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('units_reserved', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('units_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reorder_required', sa.Boolean(), nullable=True))
        batch_op.drop_column('quantity')
        batch_op.drop_column('date')
        batch_op.drop_column('days_of_supply')
        batch_op.drop_column('restock_level')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('return_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('return_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_units_sold', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customer_feedback', sa.Text(), nullable=True))
        batch_op.alter_column('return_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('return_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('region')

    with op.batch_alter_table('return_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.alter_column('return_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('return_reason',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('customer_feedback')
        batch_op.drop_column('total_units_sold')
        batch_op.drop_column('return_count')
        batch_op.drop_column('title')

    with op.batch_alter_table('inventory_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('restock_level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('days_of_supply', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('reorder_required')
        batch_op.drop_column('units_total')
        batch_op.drop_column('units_reserved')
        batch_op.drop_column('units_inbound')
        batch_op.drop_column('units_available')
        batch_op.drop_column('title')

    with op.batch_alter_table('business_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('clicks', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('impressions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.FLOAT(), nullable=True))
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('units_sold',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sessions')
        batch_op.drop_column('page_views')
        batch_op.drop_column('returns')
        batch_op.drop_column('revenue')
        batch_op.drop_column('title')

    with op.batch_alter_table('advertising_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roas', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.alter_column('acos',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sales',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('campaign_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('roi')

    # ### end Alembic commands ###
