"""add role field to user model

Revision ID: e454ebfdac94
Revises: 6c3cb342a468
Create Date: 2025-01-30 20:31:23.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e454ebfdac94'
down_revision = '6c3cb342a468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # 3. Now make it not nullable with a default value
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               nullable=False,
               existing_server_default=None,
               server_default='user')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###
